# Generated by Django 3.2.9 on 2021-11-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod',
            name='room_number',
        ),
    ]
