# Generated by Django 3.2.9 on 2021-11-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20211116_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='activity',
            field=models.CharField(max_length=15),
        ),
    ]
