# Generated by Django 3.2.9 on 2021-11-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_homeimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeImages',
        ),
    ]
