# Generated by Django 3.2.9 on 2021-11-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_delete_homeimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=25)),
                ('url_of_image', models.CharField(max_length=500)),
                ('image_redirect', models.CharField(max_length=500)),
            ],
        ),
    ]
