# Generated by Django 3.2.9 on 2021-11-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_homeimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeImage',
        ),
    ]
