# Generated by Django 3.2.9 on 2021-11-21 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20211121_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image_redirect',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image_url',
        ),
    ]
