# Generated by Django 3.2.9 on 2021-12-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20211121_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
    ]
