# Generated by Django 3.2.9 on 2021-12-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_pod_additional_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='gender_ratio',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pod',
            name='school_ratio',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pod',
            name='total_students',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
