# Generated by Django 3.2.9 on 2021-12-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20211222_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='gender_ratio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pod',
            name='school_ratio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pod',
            name='total_students',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
