# Generated by Django 3.2.9 on 2021-12-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20211222_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pod',
            old_name='school_ratio',
            new_name='school_standard_deviation',
        ),
    ]
